#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "You need to specify a tag version"
    echo "$ ./tag_release 0.3"
    exit 1
fi

git tag -a $1 -m "Released v$1, see README.md for changelog."
git push --tags
